apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ template "shenyu.fullname" . }}-admin
spec:
  selector:
    matchLabels:
      app: shenyu-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: shenyu-admin
    spec:
      containers:
        - name: shenyu-admin
          image: {{ .Values.admin.image }}:{{ default "2.4.3" .Values.admin.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 9095
          env:
            - name: 'TZ'
              value: 'Asia/Beijing'
